#!/usr/bin/env bash
# Every user-tunable value lives here; the phases only read from this file.

# ── Source repo (used by bootstrap.sh and the ISO builder) ──────────────
REPO=${REPO:-macaricol/arch}
BRANCH=${BRANCH:-main}

# ── Install media (tools/build-autoinstall-iso.sh) ─────────────────────
# Where the builder fetches the official ISO from when you don't hand it one.
# Any Arch mirror works; this is the project's own geo-balanced one.
ISO_MIRROR='https://geo.mirror.pkgbuild.com/iso/latest'

# ── Installer look ─────────────────────────────────────────────────────
# Shown under the logo (logo.txt) on every step.
TAGLINE='PACMAN · KDE Plasma'
# The 16 console colours used while installing, in VT order. Built on the
# palette 070F34 Oxford blue, 0313A6 zaffre, 9201CB violet, F715AB cerise,
# 34EDF3 cyan; the off-white text, lavender hints and error red are tints
# added for roles it has no colour for. How lib/ui.sh uses them:
#   0 background · 4 empty progress bar, unselected buttons · 8 hints
#   9 errors · 10 closing title · 11 warnings · 13 tagline
#   14 logo, tags, progress, spinner · 15 text
# Only applies on a real console (TERM=linux), not in a terminal emulator.
CONSOLE_PALETTE=(
  # black  red    green  yellow blue   magenta cyan   white
  070F34 FF3D6E 34EDF3 F715AB 0313A6 9201CB 34EDF3 B8C0E0
  6B74B8 FF3D6E 34EDF3 F715AB 3A4BFF F715AB 34EDF3 E8F1FF
)

# ── Locale ─────────────────────────────────────────────────────────────
TIMEZONE='Europe/Lisbon'
KEYMAP='pt-latin9'                   # console keymap: live ISO and installed system
X11_LAYOUT='pt'                      # Plasma keyboard layout
LOCALES=(en_US.UTF-8 pt_PT.UTF-8)    # generated by locale-gen
LANG_LOCALE='pt_PT.UTF-8'            # display language
MESSAGES_LOCALE='en_US.UTF-8'        # terminal and log messages

# ── Disk ───────────────────────────────────────────────────────────────
# Layout is always: EFI, swap sized to RAM (so hibernation works), Btrfs root
# with @ and @home subvolumes.
MIRROR_COUNTRIES='PT,ES'
EFI_SIZE='512M'
BTRFS_MOUNT_OPTS='noatime,compress=zstd:1'

# ── Packages ───────────────────────────────────────────────────────────
BASE_PACKAGES=(base linux linux-firmware btrfs-progs grub efibootmgr nano networkmanager sudo plymouth)

KDE_PACKAGES=(
  plasma-desktop sddm sddm-kcm kscreen plasma-pa plasma-nm plasma-systemmonitor
  bluedevil kdeconnect kdenetwork-filesharing kwalletmanager
  konsole dolphin ark featherpad kio-admin
  kdegraphics-thumbnailers ffmpegthumbs pipewire-jack
)

EXTRA_PACKAGES=(
  fastfetch mpv krdc krdp git code
  ttf-liberation noto-fonts-cjk
  ntfs-3g exfatprogs dosfstools   # format/repair NTFS, exFAT, FAT32 (mounting needs nothing extra)
)

GAMING_PACKAGES=(steam)  # only installed when a supported GPU was detected, see post phase
AUR_PACKAGES=(zen-browser-bin qview)

# The lib32-* packages are what Steam needs. Installing the right ones up
# front matters: steam depends on virtual lib32-vulkan-driver / lib32-libgl,
# and pacman --noconfirm would otherwise pick lib32-nvidia-utils (and with it
# the whole NVIDIA userspace) even on AMD/Intel machines.
GPU_PACKAGES_INTEL=(mesa lib32-mesa vulkan-intel lib32-vulkan-intel intel-media-driver)
GPU_PACKAGES_AMD=(mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon radeontop)
# nvidia-open, not nvidia: the proprietary kernel modules are gone from the
# repos (nvidia-open declares Replaces: nvidia<=580.119.02-2), so the old name
# is simply "target not found" and aborts the whole post phase. The non-dkms
# build is the right one here because BASE_PACKAGES installs the stock `linux`
# kernel, which it's prebuilt against. Note this only drives Turing (RTX 20xx)
# and newer — NVIDIA's 615 branch dropped Maxwell/Pascal/Volta, and with the
# proprietary package gone those cards now fall back to nouveau.
GPU_PACKAGES_NVIDIA=(nvidia-open nvidia-utils lib32-nvidia-utils nvidia-settings opencl-nvidia)
# VMs and unknown hardware. Deliberately no software Vulkan: a 64-bit Vulkan
# device (vulkan-swrast) makes the SDDM theme's video background render blank
# under VirtualBox, and lib32-vulkan-swrast can't be installed without it.
GPU_PACKAGES_FALLBACK=(mesa lib32-mesa)

# ── Audio ──────────────────────────────────────────────────────────────
# PipeWire does not upmix by default: on a surround card, stereo content
# plays out of front L/R only and the rear/side/centre speakers stay silent.
# These settings feed every speaker. Set UPMIX_SURROUND=0 on a machine with
# plain stereo output, where upmixing does nothing useful.
UPMIX_SURROUND=1
UPMIX_METHOD='psd'        # psd = matrix-decode rears from L-R; also 'simple', 'none'
UPMIX_LFE_CUTOFF=150      # Hz and below go to the subwoofer
UPMIX_FC_CUTOFF=12000     # Hz and below go to the centre speaker
UPMIX_REAR_DELAY=12.0     # ms of Haas delay on the rears, so they stay behind you

# ── Look & feel ────────────────────────────────────────────────────────
SDDM_THEME_REPO='https://github.com/macaricol/sddm-astronaut-theme.git'
SDDM_THEME='sddm-astronaut-theme'
WALLPAPER="/usr/share/sddm/themes/$SDDM_THEME/Wallpapers/cyberpunk2077.jpg"
ICON_THEME_REPO='https://github.com/L4ki/Breeze-Chameleon-Icons.git'
ICON_THEME='Breeze Chameleon Dark'   # a directory inside that repo
PLASMOID_REPOS=(                     # each repo must contain a package/ directory
  https://github.com/macaricol/kde_modernclock.git
  https://github.com/exequtic/apdatifier
)

# ── Samba ──────────────────────────────────────────────────────────────
SAMBA_WORKGROUP='WORKGROUP'
