#!/usr/bin/env bash
# Every user-tunable value lives here; the phases only read from this file.

# ── Source repo (used by bootstrap.sh and the ISO builder) ──────────────
REPO=${REPO:-macaricol/arch}
BRANCH=${BRANCH:-main}

# ── Locale ─────────────────────────────────────────────────────────────
TIMEZONE='Europe/Lisbon'
KEYMAP='pt-latin9'                   # console keymap: live ISO and installed system
X11_LAYOUT='pt'                      # Plasma keyboard layout
LOCALES=(en_US.UTF-8 pt_PT.UTF-8)    # generated by locale-gen
LANG_LOCALE='pt_PT.UTF-8'            # display language
MESSAGES_LOCALE='en_US.UTF-8'        # terminal and log messages

# ── Disk ───────────────────────────────────────────────────────────────
# Layout is always: EFI, swap sized to RAM (so hibernation works), Btrfs root
# with @ and @home subvolumes.
MIRROR_COUNTRIES='PT,ES'
EFI_SIZE='512M'
BTRFS_MOUNT_OPTS='noatime,compress=zstd:1'

# ── Packages ───────────────────────────────────────────────────────────
BASE_PACKAGES=(base linux linux-firmware btrfs-progs grub efibootmgr nano networkmanager sudo)

KDE_PACKAGES=(
  plasma-desktop sddm sddm-kcm kscreen plasma-pa plasma-nm plasma-systemmonitor
  bluedevil kdeconnect kdenetwork-filesharing kwalletmanager
  konsole dolphin ark featherpad kio-admin
  kdegraphics-thumbnailers ffmpegthumbs pipewire-jack
)

EXTRA_PACKAGES=(
  fastfetch mpv krdc krdp git code
  ttf-liberation noto-fonts-cjk
  ntfs-3g exfatprogs dosfstools   # format/repair NTFS, exFAT, FAT32 (mounting needs nothing extra)
)

GAMING_PACKAGES=(steam base-devel)  # base-devel: required to build AUR packages
AUR_PACKAGES=(zen-browser-bin qimgv-git)

# The lib32-* packages are what Steam needs. Installing the right ones up
# front matters: steam depends on virtual lib32-vulkan-driver / lib32-libgl,
# and pacman --noconfirm would otherwise pick lib32-nvidia-utils (and with it
# the whole NVIDIA userspace) even on AMD/Intel machines.
GPU_PACKAGES_INTEL=(mesa lib32-mesa vulkan-intel lib32-vulkan-intel intel-media-driver)
GPU_PACKAGES_AMD=(mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon radeontop)
GPU_PACKAGES_NVIDIA=(nvidia nvidia-utils lib32-nvidia-utils nvidia-settings opencl-nvidia)
GPU_PACKAGES_FALLBACK=(mesa lib32-mesa vulkan-swrast lib32-vulkan-swrast)  # VMs, unknown hardware

# ── Look & feel ────────────────────────────────────────────────────────
SDDM_THEME_REPO='https://github.com/macaricol/sddm-astronaut-theme.git'
SDDM_THEME='sddm-astronaut-theme'
WALLPAPER="/usr/share/sddm/themes/$SDDM_THEME/Wallpapers/cyberpunk2077.jpg"
ICON_THEME_REPO='https://github.com/L4ki/Breeze-Chameleon-Icons.git'
ICON_THEME='Breeze Chameleon Dark'   # a directory inside that repo
PLASMOID_REPOS=(                     # each repo must contain a package/ directory
  https://github.com/macaricol/kde_modernclock.git
  https://github.com/exequtic/apdatifier
)

# ── Samba ──────────────────────────────────────────────────────────────
SAMBA_WORKGROUP='WORKGROUP'
